a = input('Digite algo: ')
print(a, 'É do tipo primitivo', type(a))
print(a, 'Possui apenas números?', a.isnumeric())
print(a, 'É alfabético?', a.isalpha())
print(a, 'É alfanumérico?', a.isalnum())
print(a, 'Possui números de 0 a 9?', a.isdecimal())
print(a, 'Possui todos as palavras em minúsculo?', a.islower())
print(a, 'Só tem espaço?', a.isspace())
print(a, 'Possui apenas letras maiúsculas?', a.isupper())
print(a, 'Possui a primeira palavra maiúscula e o restante minúsculas (CAPITALIZADA)?', a.istitle())
